### ISSUE TITLE
Add support for `Associated App Keys`

### ISSUE THREAD

**Issue by Hige** [LauLamanApps/apple-passbook#3]
How set associatedStoreIdentifiers field?

**Comment by LauLaman** [comment]
This package does currently not support 
- [Associated App Keys](https://developer.apple.com/library/archive/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/TopLevel.html#//apple_ref/doc/uid/TP40012026-CH2-SW7)
- [Companion App Keys](https://developer.apple.com/library/archive/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/TopLevel.html#//apple_ref/doc/uid/TP40012026-CH2-SW8)

Will add support to this is a future version. 
You are also free to open a PR yourself

**Comment by LauLaman** [comment]
@Hige With version 1.1.1 it's now possible:

```php
$passbook->addAssociatedStoreIdentifiers(65278192);
```
