### ISSUE TITLE
Missing setters and getters for Expiration Date

### ISSUE THREAD

**Issue by ercole79** [LauLamanApps/apple-passbook#8]
I don't understand how i can set the expiration date of a event ticket
I see the property in the Passbook class, but it looks like the setter is missing

**Comment by LauLaman** [comment]
Hi @ercole79,

You are totally right!

looks like the setter and getter is missing..

do you want to open a PR?

**Comment by ercole79** [comment]
It's my first time, i tried to open a PR with just the setter
Not sure the getter would be useful

Let me know... thank you

**Comment by LauLaman** [comment]
@ercole79 a new release was created for your fix v1.1.3
